WebStore/Models/ViewModel/Roles/ChangeRoleViewModel.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebStore.Models.ViewModel.Roles
{
    public class ChangeRoleViewModel
    {
        public string UserId { get; set; }
        public string UserEmail { get; set; }
        public List<IdentityRole> AllRoles { get; set; }
        public IList<string> UserRoles { get; set; }
        public ChangeRoleViewModel()
        {
            AllRoles = new List<IdentityRole>();
            UserRoles = new List<string>();
        }
    }
}

WebStore/Controllers/Products/CategoryController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Models;
using WebStore.Models.DbModel;
using WebStore.Models.ViewModel.Category;

namespace WebStore.Controllers.Products
{
    public class CategoryController : Controller
    {
        private readonly ApplicationContext dbContext;
        private readonly IHostingEnvironment environment;

        public CategoryController(ApplicationContext dbContext, IHostingEnvironment environment)
        {
            this.dbContext = dbContext;
            this.environment = environment;
        }

        public ActionResult Index()
        {
            var categoryList = this.dbContext.Categories.ToList();
            return View(categoryList);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> CreateSubmitAsync(string name, IFormFile Image)
        {
            var newCategory = new Category()
            {
                Id = Guid.NewGuid(),
                Name = name,
                DateCreate =DateTime.Now

            };
            if (Image != null)
            {
                string falename = Image.FileName;
                string path = $"/files/{falename}";
                string serverPath = $"{this.environment.WebRootPath}{path}";
                FileStream fs = new FileStream(serverPath, FileMode.Create,
                    FileAccess.Write);
                await Image.CopyToAsync(fs);
                fs.Close();

                newCategory.Image = path;
            }

            this.dbContext.Categories.Add(newCategory);
            this.dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await this.dbContext.Categories.SingleOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            var model = new CategoryEditVm()
            {
                Id = category.Id,
                Name = category.Name,
                Image = category.Image
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditSubmit(CategoryEditVm model , IFormFile Image)
        {
            var upCat = this.dbContext.Categories
                .FirstOrDefault(c => c.Id == model.Id);

            if ( upCat == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                if (Image != null )
                {
                    string name = Image.FileName;
                    string path = $"/files/{name}";
                    string serverPath = $"{this.environment.WebRootPath}{path}";
                    FileStream fs = new FileStream(serverPath, FileMode.Create,
                        FileAccess.Write);
                    await Image.CopyToAsync(fs);
                    fs.Close();
                    upCat.Image = path;
                }
            }
            upCat.Name = model.Name;

            this.dbContext.Categories.Update(upCat);
            this.dbContext.SaveChanges();


            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            var category = this.dbContext.Categories.FirstOrDefault(cat => cat.Id == id);
            if (category != null)
            {
                var result = this.dbContext.Categories.Remove(category);
                this.dbContext.SaveChanges();

            }
            return RedirectToAction("Index");
        }
    }
}

WebStore/Controllers/RolesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Models.DbModel;
using WebStore.Models.ViewModel.Roles;

namespace WebStore.Controllers
{
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        UserManager<AccountUser> userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<AccountUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }
        public IActionResult Index()
        {
            return View(this.roleManager.Roles.ToList());
        }


        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await this.roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }



        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await this.roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await this.roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(this.userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            var user = await this.userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await this.userManager.GetRolesAsync(user);
                var allRoles = this.roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            var user = await this.userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await this.userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = this.roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await this.userManager.AddToRolesAsync(user, addedRoles);

                await this.userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUser(string userId)
        {
            var user = await this.userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var result = await this.userManager.DeleteAsync(user);
            }
            return RedirectToAction(nameof(UserList));
        }
    }
}

WebStore/Views/Roles/Create.cshtml
@model string

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Create" method="post">
    <div class="form-group">
        <label for="name">Нова роль</label>
        <input name="name" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Добавити</button>
</form>

WebStore/Views/Roles/Edit.cshtml
@model WebStore.Models.ViewModel.Roles.ChangeRoleViewModel

<div>
    <h4>Зареєстровані працівники </h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="UserId" />
                <div class="form-group">
                    <label asp-for="UserEmail" class="control-label"></label>
                    <input asp-for="UserEmail" class="form-control" />
                    <span asp-validation-for="UserEmail" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UserRoles" class="control-label"></label>
                    @*<input asp-for="UserRoles" class="form-control" />*@
                    @foreach (var role in Model.UserRoles)
                    {
                        <ul>
                            <li><input asp-for="@role" class="text-danger" /></li>
                        </ul>


                    }
                </div>

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

WebStore/Views/Roles/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>

<hr />
<div class="cont" id="container">
    <h3>Список ролей</h3>
    <hr />
    <a asp-action="Create">Добавити роль</a>
    &nbsp; &nbsp;  &nbsp;
    <a asp-action="UserList">Список користувачів</a>

</div>
<hr />



<div class="cont" id="container">

    <table class="table">
        @foreach (var role in Model)
        {
            <tr>
                <td>@role.Name</td>
                <td>
                    <form asp-action="Delete" asp-route-id="@role.Id">
                        <button type="submit" class="btn btn-sm btn-danger">
                            Удалить
                        </button>
                    </form>
                </td>
            </tr>
        }
    </table>
</div>

<style>
    #container {
        background-color: aliceblue;
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 25px;
    }
</style>

WebStore/Views/Roles/UserList.cshtml
@model IEnumerable<WebStore.Models.DbModel.AccountUser>

<div id="container">
    <div >
        &nbsp;&nbsp;&nbsp;
        <a class="cont"  asp-action="Index" asp-controller="Roles" asp-route-userid=""><b>Ролі</b></a>
        @*&nbsp;&nbsp;&nbsp;
        <a class="cont"  asp-action="UserList" asp-controller="Roles"><b>Користувачі</b></a>*@
        &nbsp;&nbsp;&nbsp;
        <a class="cont"  asp-action="Index" asp-controller="Category"><b>Категорії товарів</b></a>

    </div>
</div>
<hr />
<div id="container">
    <h3 style="text-align:center;">Кабінет Admin</h3>

</div>
<hr />
<h3>Список користувачів</h3>
<hr />

<div id="container">
    <table class="table">
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Email</td>


                <td>
                    <form asp-action="DeleteUser" asp-route-userId="@user.Id" method="post">
                        <button type="submit" class="btn btn-sm btn-danger">
                            Удалить
                        </button>
                    </form>
                </td>
                <td>
                    <a style=" background-color: #f1f1f1;" asp-action="Edit" asp-controller="Roles" asp-route-userid="@user.Id">Edit User</a>
                </td>
            </tr>
        }
    </table>
</div>

<style>
    #container {
        
        background-color: aliceblue;
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 25px;
    }

    .cont {
        width: 30%;
        margin-left: 20px;
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 5px;
        background-color: #f1f1f1;
    }

    #contMenu {
        background: #f1f1f1;
        font-weight: bold;
        float: left;
        margin-left: 15px;
        margin-right: 15px;
        margin-bottom: 50px;
        text-align: center;
        padding: 10px;
    }
</style>