WebStore/Controllers/Products/BasketController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Models;
using WebStore.Models.DbModel;

namespace WebStore.Controllers.Products
{
    public class BasketController : Controller
    {
        private ApplicationContext dbContext;

        public BasketController(ApplicationContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public ActionResult Index(Guid userId)
        {
            var userBaskets = this.dbContext.Basckets
                .Include(b => b.Product)
                .Where(b => b.UserId == userId).ToList();
            return View(userBaskets);
        }
        [HttpPost]
        public IActionResult Buy(Guid userId, Guid productId)
        {
            var product = dbContext.Products.FirstOrDefault(pr => pr.Id == productId);

            var newBascet = new Bascket()
            {
                Id = Guid.NewGuid(),
                DateRegister = DateTime.Now,
                // Number = 
                ProductId = product.Id
            };
            var count = 0;
            if (userId != Guid.Empty)
            {
                var user = dbContext.Userss.FirstOrDefault(user => user.Id == userId);
                newBascet.UserId = user.Id;

                this.dbContext.Basckets.Add(newBascet);
                this.dbContext.SaveChanges();

                var userBaskets = this.dbContext.Basckets
                .Include(b => b.Product)
                .Where(b => b.UserId == userId).ToList();

                count = userBaskets.Count;
            }
            else
            {
                //this.dbContext.Basckets.Add(newBascet);
                //this.dbContext.SaveChanges();
            }
           

           return new JsonResult(new { Count = count, Message = "Додано успішно" });
          
        }
        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            var bascket = this.dbContext.Basckets.FirstOrDefault(b => b.Id == id);
            if (bascket != null)
            {
                var result = this.dbContext.Basckets.Remove(bascket);
                this.dbContext.SaveChanges();
            }
            return RedirectToAction(nameof(Index), new { userId = bascket.UserId });
        }
    }
}

WebStore/Controllers/RolesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Models.DbModel;
using WebStore.Models.ViewModel.Roles;

namespace WebStore.Controllers
{
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        UserManager<AccountUser> userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<AccountUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }
        public IActionResult Index()
        {
            return View(this.roleManager.Roles.ToList());
        }


        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await this.roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }



        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await this.roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await this.roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(this.userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            var user = await this.userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await this.userManager.GetRolesAsync(user);
                var allRoles = this.roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            var user = await this.userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await this.userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = this.roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await this.userManager.AddToRolesAsync(user, addedRoles);

                await this.userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUser(string userId)
        {
            var user = await this.userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var result = await this.userManager.DeleteAsync(user);
            }
            return RedirectToAction(nameof(UserList));
        }
    }
}

WebStore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using WebStore.Service.LayoutData;
@inject ILayoutDataService layoutDataService;

@inject SignInManager<WebStore.Models.DbModel.AccountUser> SignInManager
@inject UserManager<WebStore.Models.DbModel.AccountUser> UserManager



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>HandMade_shop </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="padding-top: 5.5rem;">
    <header id="header">
        @*add navbar-fixed-top  - сделать верхнее меню прикрепленным *@
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light @*bg-white*@ border-bottom box-shadow mb-3 fixed-top"
             style="background-color:#E0FAE9">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" title="HandMade_shop">
                    <img Id="imgLogo1" src="~/images/homeLogo.jpg" />
                </a>
                @*<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>*@
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @{
                            var userName = UserManager.GetUserName(User);

                            string userRoles = "";
                            if (User.Identity.IsAuthenticated)
                            {

                                if (User.IsInRole("Admin"))
                                {
                                    userRoles = "Admin";
                                }
                                else if (User.IsInRole("User"))
                                {
                                    userRoles = "User";
                                }
                            }
                            if (userRoles != "" || userName != null)
                            {
                                var i = ViewBag.User;
                                var r = User.Identity.Name;


                            }
                            if (userRoles == "Admin")
                            {

                                <li><a style=" margin-right: 20px;" asp-action="UserList" asp-controller="Roles">Кабінет </a> </li>

                                //  <li><a style=" margin-right: 20px;" asp-action="Index" asp-controller="Roles">Users </a> </li>
                            }
                        }


                        <li>@Html.ActionLink("Контакти", "Contact", "Home")</li>

                        @*<li><a style=" margin-right: 20px;" asp-action="Index" asp-controller="Roles">Users </a> </li>*@




                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                    @{
                        var userId = await layoutDataService.UserIdAsync();
                        var res = layoutDataService.GetProductCountAsync().Result;

                        var count = res;

                        var resCount = count == 0 ? "" : $"({count})";

                    }

                    <div id="conteiner">
                        <a asp-action="Index" asp-controller="Basket" asp-route-userId="@userId">
                            <img style="width: 15%; margin-left:20px;" src="~/images/basket.PNG" /><span data-fieldname="headerproductscount"> @resCount</span>
                        </a>
                    </div>

                </div>

            </div>
        </nav>

    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - HandMade_shop
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>


</html>
<style>
    #imgLogo1 {
        width: 20%;
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 5px;
    }
    /*#container {
        background-color: aliceblue;
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 25px;
    }*/
</style>


@*привет. Ошибка "No service for type has been registered" указывает, что в Startup.ConfigureServices() не добавлена зависимость. Делать inject обычного списка не очень логично, я бы добавил класс который будет выгружать информацию для Layout.

    1. Создаем класс LayoutDataService. Для примера сделал с интерфейсом, можно обойтись без него.
    2. Добавляем в конструктор необходимые для выгрузки зависимости.
    Для доступа к пользователю можно использовать HttpContext (такой же как в контроллере). В asp net для этого есть специальный IHttpContextAccessor.
    3. Регистрируем в Startup.ConfigureServices() наш класс
    4. Регистрируем в Startup.ConfigureServices() IHttpContextAccessor, как указано в оф. документации https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-5.0
    5. В LayoutDataService можно в дальнейшем добавить, например, контекст базы. Всё как обычно - зависимость добавить к конструктор и зарегистрировать в Startup.
       IHttpContextAccessor -  https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-5.0
*@